### ISSUE TITLE
App is not shown after update to Android Auto 3.0

### ISSUE THREAD

**Issue by acquiles** [thekirankumar/carstream-android-auto#103]
I've installed Android Auto 3.0.570. 554
Carstream is not shown. Also Other similar apps. Like Aamirror. 
I've tried to rename package with apk editor pro. 
But still no chance. 

Any solution?

**Comment by lukasmesicek** [comment]
I must confirm, its not working :( Only the CarStream player is available

**Comment by acquiles** [comment]
Interesting that, I've downgraded to 2.9 then when I press the last icon on Android auto to reach carstream, android auto starts kind of flickering and shows black screen. Even I cannot see "return to (your car brand)" icon.
Then I've reinstall 3.0 and this icon back to normal work. Sure carstream and similar apps are not shown.

**Comment by shmykelsa** [comment]
Android Auto 3.0 is blocking custom apps.

**Comment by fortelux** [comment]
Do u think will be a fix for  car streaming with Android Auto 3.0 in the next future to unblocking it?

**Comment by shmykelsa** [comment]
Only Kiran knows

Da: fortelux<mailto:notifications@github.com>
Inviato: lunedì 19 febbraio 2018 06:39 PM
A: thekirankumar/carstream-android-auto<mailto:carstream-android-auto@noreply.github.com>
Cc: Gabriele Rizzo<mailto:gabriele.rizzo@outlook.com>; Comment<mailto:comment@noreply.github.com>
Oggetto: Re: [thekirankumar/carstream-android-auto] App is not shown after update to Android Auto 3.0 (#103)


Do u think will be a fix for car streaming with Android Auto 3.0 in the next future to unblocking it?

**Comment by thekirankumar** [comment]
No, its not possible. The only solution is to use Android Auto v2.9 via apk mirror.

**Comment by pdario** [comment]
Is there any way to prevent Google Play Store to offer the update to v3?

**Comment by shmykelsa** [comment]
Well yes, you should first downgrade and then stop automatic updates

Da: Dario Piantanida<mailto:notifications@github.com>
Inviato: martedì 20 febbraio 2018 01:25 PM
A: thekirankumar/carstream-android-auto<mailto:carstream-android-auto@noreply.github.com>
Cc: Gabriele Rizzo<mailto:gabriele.rizzo@outlook.com>; Comment<mailto:comment@noreply.github.com>
Oggetto: Re: [thekirankumar/carstream-android-auto] App is not shown after update to Android Auto 3.0 (#103)


Is there any way to prevent Google Play Store to offer the update to v3?

**Comment by pdario** [comment]
I already downgraded to v2.9, but each time I go to the list of updatable apps, AA is still there, so I can't use "update all" button. Any way to take it away from that list?

**Comment by fortelux** [comment]
@pdario u have to go on AA on the play store and pull off the flag on the right top..
![whatsapp image 2018-02-20 at 14 48 16](https://user-images.githubusercontent.com/36641644/36427365-54755872-164d-11e8-9417-4a5ca7e44d82.jpeg)

**Comment by shmykelsa** [comment]
No

Da: Dario Piantanida<mailto:notifications@github.com>
Inviato: martedì 20 febbraio 2018 01:34 PM
A: thekirankumar/carstream-android-auto<mailto:carstream-android-auto@noreply.github.com>
Cc: Gabriele Rizzo<mailto:gabriele.rizzo@outlook.com>; Comment<mailto:comment@noreply.github.com>
Oggetto: Re: [thekirankumar/carstream-android-auto] App is not shown after update to Android Auto 3.0 (#103)


I already downgraded to v2.9, but each time I go to the list of updatable apps, AA is still there, so I can't use "update all" button. Any way to take it away from that list?
