### ISSUE TITLE
Cant see car stream

### ISSUE THREAD

**Issue by skrajubsnl** [thekirankumar/carstream-android-auto#125]
When i connect the phone to the car, Android auto starts up. So far, so good. When i press the button at the bottom right side, the button to go to carstream is disappear...

Is there a fix???

**Comment by skrajubsnl** [comment]
Cloned app installed

**Comment by nameor123** [comment]
@skrajubsnl #116

**Comment by JHawk88** [comment]
Also dealing with similar issue. Was the app blocked by Android Auto again?

**Comment by alex4108** [comment]
Reproducing here as well.

App 1.8.3
OS 7.0
Auto 3.0.570544-release
