### ISSUE TITLE
2017 Subaru XV still blocked

### ISSUE THREAD

**Issue by ZeeBarry** [thekirankumar/carstream-android-auto#133]
Can't seem to unblock. I've followed the instrutions on the video about editing using apk editor Pro (no longer available in Gplay btw) and followed the instructions properly. Still can't seem to get the app to show in the car. HELP PLEASE. I've also made sure my android app is in developer mode and still can't see carstream on the car screen. 
![photo_2018-03-09_21-34-11](https://user-images.githubusercontent.com/37212933/37205804-eaea5a72-23e1-11e8-931d-df9ba7f2075a.jpg)

**Comment by shmykelsa** [comment]
See issue #116
Or
Uninstall Android Auto 3.0, Install Android Auto 2.9 or below, disable automatic updates on Play Store's Android Auto Page, re-enable unknown sources

**Comment by ZeeBarry** [comment]
I just tried installing 2.9 apk, but it says it's not compatible with my phone . Samsung Galaxy S7 running android version 7.0

**Comment by ZeeBarry** [comment]
>See issue #116 

Finally got through to those websites. Will have to grab my windows laptop because currently on my mac. Will keep you posted. Thank you for the reply.

**Comment by ZeeBarry** [comment]
Got it working!!!!! on 3.0! All i had to do was follow those prompts on the link you had sent me and it worked! thank you so much!
