### ISSUE TITLE
Peugeot 5008

### ISSUE THREAD

**Issue by ianvlynch** [thekirankumar/carstream-android-auto#140]
Not sure if I am doing something wrong but I have tried the edits using the editor pro and I can't get the last button on android auto to show carstream optuon

**Comment by shmykelsa** [comment]
If you happen to have Android Auto 3.0, you should follow issue #116 or, alternatively, uninstall Android Auto, install version 2.9 or below, disable automatic updates, install the app by modifying the package name (APK Editor or App Cloner) and re-activate unknown sources

**Comment by ianvlynch** [comment]
Thank you how do I I stall an older version of Android auto?

**Comment by ianvlynch** [comment]
Thank you how do I I stall an older version of Android auto?

**Comment by ianvlynch** [comment]
Used android worked a treat thank you

**Comment by shmykelsa** [comment]
Please close the issue if solved
