### ISSUE TITLE
Carstream blocked again by google wile being on AA 2.9?

### ISSUE THREAD

**Issue by fmsidoe** [thekirankumar/carstream-android-auto#153]
On my phone i have AA 2.9 to use carstream.
But few days ago carstreamed stopped appearing in the right menu. It is still visible in the list of music players.

I checked my AA version and it still 2.9.
But I saw another change. While running AA in the car, I see now the screen on my phone: Swipe to unlock.
Instead of only showing AA logo.

Saw this article few days ago:
https://www.digitaltrends.com/cars/android-auto-swipe-to-unlock/

A new feature has been rolled out to android auto, but my AA is still 2.9.
Probably a google (service) app has been updated that might block carstream.

Also tried changing the name with APK editor pro. Still not working...
Does anyone know how to bypass this? or what the problem is?

**Comment by shmykelsa** [comment]
Try to take a look at issue #116 and see if it helps

**Comment by fmsidoe** [comment]
Yes it works!!! now on AA3.0 with CarStream
Thanks @shmykelsa
