### ISSUE TITLE
not able to find auto folder in appdata folder

### ISSUE THREAD

**Issue by AKDara** [thekirankumar/carstream-android-auto#201]
I'm able to open the folder c:\users\USERNAME\AppData\Local\Android\Sdk\extras\google
but after this not able to see the Auto folder.
Am I missing something or do I need to install something?

**Comment by as4ysf** [comment]
refer to https://github.com/thekirankumar/carstream-android-auto/issues/189

**Comment by KirGro** [comment]
What does #189 have to do with this?

**Comment by LeaderHC** [comment]
Sorry, but I have the same doubts with AKDara, I dont understand what #189 have to do with this?

**Comment by AKDara** [comment]
I understood that, along with android studio we need to install android auto emulator then the required folder appears and rest of the steps can be followed.

**Comment by LeaderHC** [comment]
KirGro, 
The emulator is into Android Studio. This program are disposal on web. 
To access this emulator you need:
1 Open Android Studio 
2 Click in Configure on right down the page
3 SDK Manager
4 SDK Platform table, certified your correct system was flag/selected
5 SDK Tools table, flag/selection option "Android Auto Desktop Head Unit emulator﻿"

All,
I can found the way to c:\users\USERNAME\AppData\Local\Android\Sdk\extras\google\auto>, but when I executed "desktop-head-unit", doens't not conclued and showing mensage: Connecting over ADB to localhost:5277... failed. Failed to start Google Automotive Link.

PS. I'm using Android Studio v.2.3.3
