### ISSUE TITLE
Replace Current Web Browser w/ Chromium?

### ISSUE THREAD

**Issue by Froppy-Dev** [thekirankumar/carstream-android-auto#95]
Is there any way to implement a full-blown version of Chromium (Chrome) instead of utilizing Webview?

**Comment by cmeka** [comment]
AFAIK Android Auto only allows WebView however you can use the Chrome engine in the developer settings by choosing the WebView implementation. If you want to use the Chrome app I would look at AAMirror.

**Comment by thekirankumar** [comment]
Absolutely right. Closing.
